import Footer from "../components/Footer";
import Header from "../components/Header";
import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "[DEV] YAIST V2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <div className="flex flex-col min-h-screen justify-between">
            <div className="flex flex-col">
              <Header />
              <div className="container mx-auto max-w-6xl">
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
